Profiles:
  MultiOrgsChannel:
    Consortium: SampleConsortium
    Application:
      Organizations:
      - Name: Org1MSP
        ID: Org1MSP
        MSPDir: crypto-config/peerOrganizations/org1/msp
        AnchorPeers:
        - Host: peer0.org1
          Port: 7051
        - Host: peer1.org1
          Port: 7051
      - Name: Org2MSP
        ID: Org2MSP
        MSPDir: crypto-config/peerOrganizations/org2/msp
        AnchorPeers:
        - Host: peer0.org2
          Port: 7051
        - Host: peer1.org2
          Port: 7051
  MultiOrgsOrdererGenesis:
    Orderer:
      OrdererType: kafka
      Addresses:
      - orderer0.orgorderer1:7050
      BatchTimeout: 2s
      BatchSize:
        MaxMessageCount: 1000
        AbsoluteMaxBytes: 103809024
        PreferredMaxBytes: 524288
      Kafka:
        Brokers:
        - kafka0.kafka:9092
        - kafka1.kafka:9092
        - kafka2.kafka:9092
        - kafka3.kafka:9092
      Organizations:
      - Name: OrdererOrg
        ID: Orderer0MSP
        MSPDir: crypto-config/ordererOrganizations/orgorderer1/msp
    Consortiums:
      SampleConsortium:
        Organizations:
        - Name: Org1MSP
          ID: Org1MSP
          MSPDir: crypto-config/peerOrganizations/org1/msp
          AnchorPeers:
          - Host: peer0.org1
            Port: 7051
          - Host: peer1.org1
            Port: 7051
        - Name: Org2MSP
          ID: Org2MSP
          MSPDir: crypto-config/peerOrganizations/org2/msp
          AnchorPeers:
          - Host: peer0.org2
            Port: 7051
          - Host: peer1.org2
            Port: 7051
Organizations:
- Name: OrdererOrg
  ID: Orderer0MSP
  MSPDir: crypto-config/ordererOrganizations/orgorderer1/msp
- Name: Org1MSP
  ID: Org1MSP
  MSPDir: crypto-config/peerOrganizations/org1/msp
  AnchorPeers:
  - Host: peer0.org1
    Port: 7051
  - Host: peer1.org1
    Port: 7051
- Name: Org2MSP
  ID: Org2MSP
  MSPDir: crypto-config/peerOrganizations/org2/msp
  AnchorPeers:
  - Host: peer0.org2
    Port: 7051
  - Host: peer1.org2
    Port: 7051
Orderer:
  OrdererType: kafka
  Addresses:
  - orderer0.orgorderer1:7050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 1000
    AbsoluteMaxBytes: 103809024
    PreferredMaxBytes: 524288
  Kafka:
    Brokers:
    - kafka0.kafka:9092
    - kafka1.kafka:9092
    - kafka2.kafka:9092
    - kafka3.kafka:9092
  Organizations:
  - Name: OrdererOrg
    ID: Orderer0MSP
    MSPDir: crypto-config/ordererOrganizations/orgorderer1/msp
