Profiles:
    MultiOrgsOrdererGenesis:
        Orderer:
            <<: *OrderersDefaults
#            OrdererType: kafka
#            Addresses:
#                - orderer0-orgorderer.kafka:7050
##                - orderer1-orgorderer.kafka:7050
            Organizations:
                - *OrgOrderer
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *Org1
                    - *Org2
    MultiOrgsChannel:
        Consortium: SampleConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Org1
                - *Org2
Organizations:
    - &OrgOrderer
        Name: OrgordererMSP
        ID: OrgordererMSP
        MSPDir: crypto-config/ordererOrganizations/orgorderer/msp
    - &Org1
        Name: Org1MSP
        ID: Org1MSP
        MSPDir: crypto-config/peerOrganizations/org1/msp
        AnchorPeers:
            - Host: peer0.org1
              Port: 7051
    - &Org2
        Name: Org2MSP
        ID: Org2MSP
        MSPDir: crypto-config/peerOrganizations/org2/msp
        AnchorPeers:
            - Host: peer0.org2
              Port: 7051
Orderer: &OrderersDefaults
    OrdererType: kafka
    Addresses:
        - orderer0.orgorderer:7050
        - orderer1.orgorderer:7050
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 1000
        AbsoluteMaxBytes: 103809024 # 99 * 1024 * 1024 B
        PreferredMaxBytes: 524288 # 512 * 1024 B
    Kafka:
        Brokers:
            - kafka0.kafka:9092
            - kafka1.kafka:9092
            - kafka2.kafka:9092
            - kafka3.kafka:9092
    Organizations:
Application: &ApplicationDefaults
    Organizations:
