# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer in Org1
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: orgorderer
    Specs:
      - Hostname: orderer0
      - Hostname: orderer1

PeerOrgs:

  - Name: Org1
    Domain: org1
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Org2
    Domain: org2
    Template:
      Count: 1
    Users:
      Count: 1
