apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: org1
  name: cli
spec:
  selector:
    matchLabels:
      app: cli
  replicas: 1
  template:
    metadata:
      labels:
        app: cli
    spec:
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/hostname: ip-172-31-33-147
      containers:
        - name: cli
          imagePullPolicy: IfNotPresent
          image: hyperledger/fabric-tools:x86_64-1.1.0
          workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer
          volumeMounts:
            - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
              name: crypto
            - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
              name: scripts
            - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
              name: channel-artifacts
            - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/chaincode
              name: chaincode
            - mountPath: /var/run/docker.sock
              name: docker-sock
              readOnly: false
          env:
            - name: CORE_VM_ENDPOINT
              value: unix:///var/run/docker.sock
            - name: CORE_PEER_ID
              value: peer0.org1
            - name: CORE_LOGGING_LEVEL
              value: DEBUG
            - name: CORE_PEER_ADDRESS
              value: peer0.org1:7051
            - name: CORE_PEER_LOCALMSPID
              value: Org1MSP
            - name: CORE_PEER_TLS_ENABLED
              value: "true"
            - name: CORE_PEER_TLS_CERT_FILE
              value: "/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1/peers/peer0.org1/tls/server.crt"
            - name: CORE_PEER_TLS_KEY_FILE
              value: "/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1/peers/peer0.org1/tls/server.key"
            - name: CORE_PEER_TLS_ROOTCERT_FILE
              value: "/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1/peers/peer0.org1/tls/ca.crt"
            - name: CORE_PEER_MSPCONFIGPATH
              value: "/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1/users/Admin@org1/msp"
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "while true; do sleep 30; done;" ]
      volumes:
        - name: crypto
          hostPath:
            path: /data/driving-files/crypto-config
        - name: scripts
          hostPath:
            path: /data/driving-files/scripts
        - name: channel-artifacts
          hostPath:
            path: /data/driving-files/channel-artifacts
        - name: chaincode
          hostPath:
            path: /data/chaincode
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock